### ISSUE TITLE
Low Memory Fortran to C Order Conversion

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/fastremap#1]
It's a common problem to convert between Fortran and C order in numpy in part because the transposition creates a large copy. It should be possible to perform this operation in-place using only a few extra bytes of memory for holding temporary variables.

**Comment by william-silversmith** [comment]
@jingpengw can you elaborate on the situation (e.g. dimensions, datatype) that is causing you a large copy? I did a small bit of googling on the in-place matrix transposition problem, and it seems like O(1) is only easy to do in square matrices. I want to make sure we don't spend too much time on a problem that numpy has already optimized. However, I suspect that we will probably be able to achieve a large reduction compared to numpy (if numpy is O(nm) then we can probably get to O(n+m) or some such).

https://en.wikipedia.org/wiki/In-place_matrix_transposition

**Comment by william-silversmith** [comment]
That's okay, this has been a problem for other people in the past too (e.g. Ran). Even if we just leave it open, it would be good to record the inputs that cause the problem.

**Comment by william-silversmith** [comment]
For example, if the dimensions you are transposing happen to be square, it would be easy to write the in-place algorithm for that.

**Comment by jingpengw** [comment]
For symmetry, it is just X == Y, we don't need Z == X ==Y, right?

**Comment by william-silversmith** [comment]
This is being handled in #3

**Comment by william-silversmith** [comment]
Resolved in #3
