### ISSUE TITLE
3d small object cannot removed when use cc3d. connected-compoenents? 

### ISSUE THREAD

**Issue by selvakarna** [seung-lab/fastremap#11]
How to set threshold for remove small 3d volume? if i increase threshold as 10000 , its error. can you share sample code remove , unwanted small 3d volume?

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Error:

after mask ids [2, 3] [1127956828     113799       1380          1     104888]
Traceback (most recent call last):
  File "sk.py", line 183, in <module>
    vlm=volum2boundary(files)
  File "sk.py", line 113, in volum2boundary
    cc_labels[cc_labels,mask_ids]=0
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (301,1936,1936) (2,)
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

so how to remove unwanted 3d volume ? which parameter based , to remove ?

@william-silversmith

**Comment by william-silversmith** [comment]
You can do:

```python
import fastremap

mask_ids = [1127956828, 113799, 1380, 1, 104888]
cc_labels = fastremap.mask(cc_labels, mask_ids)
```

**Comment by william-silversmith** [comment]
Also, I think the code you shared above doesn't look right. It should be...

```python
cc_labels[ np.isin(cc_labels, mask_ids) ] = 0
```

**Comment by selvakarna** [comment]
@william-silversmith , thanks , i will check .

**Comment by selvakarna** [comment]
Hi @william-silversmith 

 where removed unwanted object from below code?  can you please clear my doubts ?



dust_threshold=2000
    cc_labels =imb
    cc_segids, pxct = np.unique(cc_labels, return_counts=True)
    mask_ids = [ sid for sid, ct in zip(cc_segids, pxct) if ct < dust_threshold and sid != 0 ]
    print('after mask ids',mask_ids,pxct)
    cc_labels[cc_labels,mask_ids]=0
    cc_labels=fastremap.mask(cc_labels,mask_ids)

**Comment by william-silversmith** [comment]
You'll want to pick one strategy or the other. `fastremap.mask` is a replacement for the numpy version.

```python
dust_threshold = 2000
cc_labels = imb
cc_segids, pxct = np.unique(cc_labels, return_counts=True)
mask_ids = [ sid for sid, ct in zip(cc_segids, pxct) if ct < dust_threshold and sid != 0 ]
print('after mask ids',mask_ids,pxct)
cc_labels=fastremap.mask(cc_labels,mask_ids)
```

**Comment by selvakarna** [comment]
Hi @william-silversmith , i got same error

after mask ids [2, 3] [1127956828     113799       1380          1     104888]
Traceback (most recent call last):
  File "sk.py", line 194, in <module>
    vlm=volum2boundary(files)
  File "sk.py", line 119, in volum2boundary
    cc_labels[cc_labels,mask_ids]=0
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (301,1936,1936) (2,)

**Comment by william-silversmith** [comment]
Make sure you delete the line:
```
cc_labels[cc_labels,mask_ids]=0
```

**Comment by selvakarna** [comment]
Yes @william-silversmith , i understood. thanks for lot support. :

**Comment by selvakarna** [comment]
Thanks @william-silversmith ,

**Comment by selvakarna** [comment]
i have doubt @william-silversmith ....

**Comment by william-silversmith** [comment]
Are the pieces not being masked?

**Comment by selvakarna** [comment]
@william-silversmith , from this package , instantly extract 3d volume ?from DICOM data sets?

**Comment by william-silversmith** [comment]
Are you trying to get one or a few labels from a messy DICOM image? I have not used DICOM but if the image is in numpy that's fine. You can also use this code:

```python
extracted_image = (cc_labels == 5) # in this example 5 is the id we want
```
If you want to extract more than one at a time, try this:

```python
extracted_image = fastremap.mask_except(cc_labels, [ 5, 6, 7, 8 ])
```
I can't be more specific though without knowing what you are trying to do though.

**Comment by selvakarna** [comment]
HI , @william-silversmith , i got same memory error ? from below ? how to solve ?

   **cc_segids, pxct = np.unique(cc_labels, return_counts=True)**


ret = _unique1d(ar, return_index, return_inverse, return_counts)
    mask = np.empty(aux.shape, dtype=np.bool_)
MemoryError
