### ISSUE TITLE
Memory Error when i convert np.unique using ? how to resolve memory error?

### ISSUE THREAD

**Issue by selvakarna** [seung-lab/fastremap#12]
Memory Error when i convert np.unique using ? how to resolve memory error?
HI , @william-silversmith , i got same memory error ? from below ? how to solve ?

cc_segids, pxct = np.unique(cc_labels, return_counts=True)

ret = unique1d(ar, return_index, return_inverse, return_counts)
mask = np.empty(aux.shape, dtype=np.bool)
MemoryError

**Comment by william-silversmith** [comment]
If you recently started getting it, you can try restarting your computer to reduce fragmentation. However, I also wrote a faster, lower memory version of np.unique.... This is a hack but you can try the following:

```bash
pip install kimimaro
```

```python
import kimimaro.skeletontricks
cc_segids, pxct = kimimaro.skeletontricks.unique(cc_labels, return_counts=True)
```

**Comment by william-silversmith** [comment]
Hi @selvakarna, did this work for you? If so, can I close these issues? Thanks!
