### ISSUE TITLE
fastremap needs C++ headers to pip install on OS X

### ISSUE THREAD

**Issue by ceesem** [seung-lab/fastremap#13]
fastremap doesn't pip install on OS X (10.4.5 Mojave) without setting the flag -stdlib=libc++ during install (for instance, `CFLAGS='-stdlib=libc++' pip install fastremap`). This is particularly a problem when installing something for which fastremap is a dependency, namely cloudvolume.

**Comment by william-silversmith** [comment]
Hi Casey, I compiled and uploaded binaries for 2.7, 3.5, 3.6, and 3.7. Try it again. For some reason, I only had trouble compiling for 3.5.

**Comment by william-silversmith** [comment]
Closing this since it seems to have disappeared as an issue after I uploaded binaries. Please reopen if it's still bothering you.
