### ISSUE TITLE
How to export STEP from Volume /SUrf?Mesh?

### ISSUE THREAD

**Issue by selvakarna** [seung-lab/fastremap#16]
How to export STEP from Volume /SUrf?Mesh?

**Comment by william-silversmith** [comment]
Hi Selvakarna,

I'm not sure what STEP means, but you can extract surface meshes using this
library:

https://github.com/seung-lab/zmesh

You can export them as OBJs and then they can be viewed in many programs.

**Comment by william-silversmith** [comment]
Closing this issue as we treated it in the zmesh issues.
