### ISSUE TITLE
inverse_component_map seems to skip entries

### ISSUE THREAD

**Issue by sdorkenw** [seung-lab/fastremap#27]
I found that `fastremap.inverse_component_map` is skipping entries in the partner array. 

Two examples with what I think it should return:
```
fastremap.inverse_component_map([ 1, 1, 1, 3 ], [ 4, 4, 5, 6 ]) 
# Returns: defaultdict(list, {1: [4], 3: [6]})
# Should return: defaultdict(list, {1: [4, 5], 3: [6]})
```

```
fastremap.inverse_component_map([ 1, 1, 1, 1 ], [ 4, 2, 5, 6 ]) 
# Returns: defaultdict(list, {1: [4]})
# Should return: defaultdict(list, {1: [4, 2, 5, 6]})
```

**Comment by william-silversmith** [comment]
Thanks for the bug report! I'll get this fixed.

**Comment by william-silversmith** [comment]
Okay, found the bug. The `continue` condition on the for loop was only checking the parent labels and not both sides.

**Comment by william-silversmith** [comment]
fastremap 1.11.4 is out with the fix.
