### ISSUE TITLE
Should build against oldest possible numpy version

### ISSUE THREAD

**Issue by jbms** [seung-lab/fastremap#29]
When a C extension is built against the NumPy headers, it requires a NumPy ABI version >= the version against which it is built.

To produce binary wheels that are maximally compatible, you should build against the oldest version of NumPy possible.

There is a meta package `oldest-supported-numpy` that you can use as a build dependency in place of `numpy`.  That will pull in the oldest version of numpy that is still considered supported.  Unless you are using particularly recent numpy API features, that should work just fine.

**Comment by william-silversmith** [comment]
Thanks Jeremy! This issue is extremely frustrating for me, I didn't know
that ABI compatibility was preserved like that. I'll start integrating this
advice into my releases.
