### ISSUE TITLE
fastremap 1.13.2 arm64 macOS: ModuleNotFoundError: No module named 'fastremap'

### ISSUE THREAD

**Issue by psobolewskiPhD** [seung-lab/fastremap#31]
Setting up a fresh arm64 python 3.9 conda on macOS 12.4 M1 and doing:
`pip install fastremap` installs `fastremap-1.13.2-cp39-cp39-macosx_10_9_universal2.whl`
It's awesome that there is now a fat binary for macOS, but...
it doesn't import:
```python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00) 
[Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastremap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fastremap'
```
It is installed:
```
 pip show fastremap                                              (test-env) ─╯
Name: fastremap
Version: 1.13.2
Summary: Remap, mask, renumber, unique, and in-place transposition of 3D labeled images. Point cloud too.
Home-page: https://github.com/seung-lab/fastremap/
Author: William Silversmith
Author-email: ws9@princeton.edu
License: LGPLv3
Location: /Users/piotrsobolewski/Dev/miniforge3/envs/test-env/lib/python3.9/site-packages
Requires: numpy
Required-by: 
```
Installing 1.12.2 which builds from source on python 3.9 or installing 1.13.0 which also has a universal2 wheel works.

Edit:
If I install using conda:
`fastremap                 1.13.2           py39hc86685f_0    conda-forge`
it imports and appears to work fine...
So it's not a 1.13.2 bug per se, but something with the build on pypi?
Edit2:
Seems like it, because using `--no-binary` and building 1.13.2 from source works fine.
Edit3:
I don't see where those universal2 wheels are coming from, as CI seems to only build x86:
https://github.com/seung-lab/fastremap/runs/7034737842?check_suite_focus=true#step:4:573
Edit4:
They're certainly bugged though:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/76622105/179336217-462ac6c9-8a07-4600-89f4-d3a5479515af.png">
<8 kb?
Edit5:
The file size of 3.8 and 3.10 wheels is fine and both work fine in fresh 3.8 and 3.10 conda envs. So the issue is just with a broken 3.9 macos-universal2 wheel upload.

**Comment by william-silversmith** [comment]
Ah, I don't build universal wheels on conda, though maybe I can start. I build them manually on my laptop so I must have screwed up the 3.9 wheel.

**Comment by william-silversmith** [comment]
Thank you for debugging this issue!

**Comment by william-silversmith** [comment]
I'm a little sleepy now so I'll deal with creating a new version update soon. I deleted the problematic universal2 wheel from PyPI so now it'll at least install from source.

**Comment by william-silversmith** [comment]
Sorry it took me a while to get back to this, but I've re-released these binaries in 1.13.3. I tested that I was able to install the universal2 binaries on M1 using arm64 and `import fastremap`.

**Comment by psobolewskiPhD** [comment]
Works fine on my end too! Thanks a ton!
❤️

**Comment by LotusWang0723** [comment]
Apple M2 Pro, 14.4.1, python 3.9, use 
conda install fastremap==1.13.2 
could install fastremap

**Comment by william-silversmith** [comment]
Hi! There are newer versions of fastremap. Would you be able to give those a try?
