### ISSUE TITLE
fastremap.unique returns an incorrect counts if applied to a large image

### ISSUE THREAD

**Issue by ivonindima** [seung-lab/fastremap#37]
The function fastremap.unique returns an incorrect counts if applied to a large image. This happens on Windows if the number of voxels in any phase exceeds the maximum allowable value for np.uint32 (4_294_967_295). 
For me the problem was solved by replacing uint32 with uint64 in unique_via_array.

```
import fastremap

N = 2500
img = np.random.randint(2, size=(N, N,N), dtype=np.uint8)
vals, counts = fastremap.unique(img, return_counts=True)
print(vals, counts/img.size) # Expected [0 1] [0.5 0.5]
```

**Comment by yojeep** [comment]
I have the same question

**Comment by william-silversmith** [comment]
For some reason, the obvious way to make this work with cython templates didn't work. I'm hesitant to simply just bump np.uint32 to np.uint64 because it will inflate memory usage significantly in some cases. Will think about this.

**Comment by yojeep** [comment]
Can you provide a vision of np.uint64 to use? For example fastremap.unique64, please?

**Comment by william-silversmith** [comment]
I found a way to do it without causing memory to explode in some variations, so I'll release that.

**Comment by william-silversmith** [comment]
@yojeep the new version is released on PyPI. Enjoy!

**Comment by yojeep** [comment]
It works.Thank you!
