### ISSUE TITLE
Mask out all except labels

### ISSUE THREAD

**Issue by manuel-castro** [seung-lab/fastremap#8]
It would be sweet if there were a function that does the opposite of mask, i.e. given some labels mask out everything else but these labels

**Comment by william-silversmith** [comment]
You can do this with

arr[~np.isin(ids)] = 0

but yes, we should include this option

**Comment by william-silversmith** [comment]
What would you like to call the function? `mask_except`? `reveal`?

**Comment by manuel-castro** [comment]
`Mask_except` is the good but boring choice

**Comment by william-silversmith** [comment]
I'm going to write this in the simplest way that should still give okay performance. If you need more speed we can write it with its own for loop logic.
